config/routes.rb
Rails.application.routes.draw do
  
  get 'static/privacy'

# Fb Authentication
  get 'auth/index'
  get 'auth/new'

  root to: 'visitors#index'

# Search bar  
  get 'visitors/search', to: 'visitors#search', :as => 'search'
  post 'visitors/track', to: 'visitors#track', :as => 'tracks'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get 'privacy-policy', to: 'static#privacy', :as => 'privacy'
  
end

app/models/track.rb
class Track < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
  	where(provide: auth.provider, uid: auth.uid).first_or_create do |user|
	  user.provide = auth.provider
	  user.uid = auth.uid
	  user.name = auth.info.name
	  user.oauth_token = auth.credentials.token
	  user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	  user.save!
	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def index
  	@appid = 951518638209199
  	if TEST
  		@test_users = Koala::Facebook::TestUsers.new(:app_id => '1441096312843702', :secret => "9ef0c28a9f94f553ae5a74165b0b03e8")
  	else
  		@graph = Koala::Facebook::API.new(current_user.oauth_token)
  	end
  end

  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def privacy
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
TEST = true
before_action :check_log unless TEST
	def index
		@search = Track.new
	end
	def search
		
	end
	def track
		#default username set as of now 
		@user = FbGraph::User.new('', :access_token => '')
		redirect_to :action => 'search'
	end
	
	private
		def release
			 params.require(:track).permit(:query)
		end

		def check_log
			redirect_to auth_index_path if current_user.nil?
		end
end

app/views/layouts/_fotter.html.erb
<ul class="nav navbar-nav">
	<li><%= link_to 'About', page_path('about') %></li>
	<li><%= link_to 'Privacy Policy', privacy_path %></li>
</ul>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'logo' do %>
        <img src="/assets/logo.png">
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'About', page_path('about') %></li>
<li>
  	<% if current_user %>
    	Welcome <strong><%= current_user.name %></strong>!
    	<%= link_to "Sign out", signout_path, id: "sign_out" %>
  	<% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ask Facebook" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Bootstrap" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer>
      <div class="container">
        <hr>
        <%= render 'layouts/fotter' %>
      </div>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<div class="container">
	<h3>About Social Query</h3>
</div>

app/views/visitors/index.html.erb
<div class="container">
	<div class="row">
		<div class="jumbotron">
			<h2>Ask facebook question in natural language</h2>
			<p></p>
			<%= simple_form_for(@search, html: { novalidate: true }) do |f| %>
			  <%= f.input :query, :placeholder => 'Start type your question', :input_html => {:class => 'form-control input-lg' }, :label => false %>
			  <span id="helpBlock" class="help-block">
			  	Example question: 
			  		Who of my friend like bob dylan,
			  </span>
			  <%= f.button :submit %>
			<% end %>
		</div>
	</div>
</div>

app/views/visitors/search.html.erb
Searching ...